// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCykgZn1VeBeziI7Ip2BjhDxeTQWWXM8',
    appId: '1:926374806186:web:4df630dcca66642f3bc6d3',
    messagingSenderId: '926374806186',
    projectId: 'bazar-9e899',
    authDomain: 'bazar-9e899.firebaseapp.com',
    storageBucket: 'bazar-9e899.firebasestorage.app',
    measurementId: 'G-P4509NR8VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwATGW1XRof-RmfhhqDZtItpsZBfUvbkU',
    appId: '1:926374806186:android:1d2fd56cd6c9facc3bc6d3',
    messagingSenderId: '926374806186',
    projectId: 'bazar-9e899',
    storageBucket: 'bazar-9e899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1u4KTXIcwr-nvCb28_HW2U27qZvSy64o',
    appId: '1:926374806186:ios:91e43c22ed418af83bc6d3',
    messagingSenderId: '926374806186',
    projectId: 'bazar-9e899',
    storageBucket: 'bazar-9e899.firebasestorage.app',
    iosBundleId: 'com.example.bazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADCykgZn1VeBeziI7Ip2BjhDxeTQWWXM8',
    appId: '1:926374806186:web:f00bf938e885209f3bc6d3',
    messagingSenderId: '926374806186',
    projectId: 'bazar-9e899',
    authDomain: 'bazar-9e899.firebaseapp.com',
    storageBucket: 'bazar-9e899.firebasestorage.app',
    measurementId: 'G-7P4FVXBXCH',
  );
}
